language: php

php:
  - '7.1'
  - '7.2'

services:
  - mysql

before_install:
  - mysql -e 'CREATE DATABASE family_test;'

install: composer install

before_script:
  - cp .env.example .env
  - php artisan key:generate

env:
  - DB_USERNAME=root
  - DB_PASSWORD=